---
# Tasks to set up WordPress folder structure and configuration

# Ensure the base WordPress directory exists
- name: Ensure WordPress base directory exists
  ansible.builtin.file:
    path: "{{ wp_base_path }}"
    state: directory
    owner: "{{ wp_deploy_user }}"
    group: "{{ wp_deploy_group }}"
    mode: "0755"
  tags:
    - setup

# Create essential directories
- name: Create WordPress subdirectories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ wp_deploy_user }}"
    group: "{{ wp_deploy_group }}"
    mode: "0755"
  with_items:
    - "{{ wp_base_path }}/wp-content"
    - "{{ wp_base_path }}/wp-content/plugins"
    - "{{ wp_base_path }}/wp-content/themes"
    - "{{ wp_base_path }}/wp-content/uploads"
    - "{{ wp_base_path }}/logs" # Optional
    - "{{ wp_base_path }}/tmp" # Optional
  tags:
    - setup

# Upload wp-config.php template
- name: Upload wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wp_base_path }}/wp-config.php"
    owner: "{{ wp_deploy_user }}"
    group: "{{ wp_deploy_group }}"
    mode: "0640"
  tags:
    - config

# Deploy .htaccess template
- name: Deploy .htaccess file
  ansible.builtin.template:
    src: htaccess.j2
    dest: "{{ wordpress_base_path }}/.htaccess"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: "0644"
  tags:
    - config
    - wordpress

# Install WP-CLI
- name: Install WP-CLI
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/bin/wp
    mode: "0755"
  tags:
    - wordpress
    - setup

- name: Install WP-CLI tab completions
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash
    dest: /etc/bash_completion.d/wp-completion.bash
    mode: "0644"
  tags:
    - wordpress
    - setup

# Rollback tasks (clean up directories in case of failure)
- name: "Rollback: Remove WordPress directory"
  ansible.builtin.file:
    path: "{{ wp_base_path }}"
    state: absent
  when: wp_rollback | default(False)
  tags:
    - rollback
